### ISSUE TITLE
link disconnected

### ISSUE THREAD

**Issue by aoki1980taichi** [egison/www.egison.org#23]
You cannot jump to correctly to "Math" and "Blog" pages from the top navbar in http://console.egison.org/ nor http://try.egison.org/ . I see 500 Internal Server Error.

**Comment by egisatoshi** [comment]
Thank you for your issue!
I fixed the link by changing the URLs of the online console and tutorial as follows:
https://www.egison.org/console.html
https://www.egison.org/try.html
